export interface DemoSystemTemplate {
  systemName: string;
  whatItDoes: string;
  intendedPurpose: string;
  industry: string;
  deploymentLocations: string;
  whoUsesIt: string;
  whoIsAffected: string;
  makesDecisionsAboutPeople: boolean;
  processesPersonalData: boolean;
  processesSensitiveData: boolean;
  affectedRegulatedAreas: string[];
  humanOversightDegree: "in-the-loop" | "on-the-loop" | "over-the-loop";
  modelProvider: string;
  decisionsAutomated: boolean;
  unstructuredNotes: string;
  regulatoryFocus: string;
  expectedTier: string;
}

export const DEMO_ARCHETYPES: DemoSystemTemplate[] = [
  {
    systemName: "TalentScan Pro Candidate Screener",
    whatItDoes: "Automated candidate resume parsing, semantic skill matching, and video interview sentiment scoring for hiring pipelines.",
    intendedPurpose: "Screen incoming applicant resumes and rank candidates for corporate engineering, finance, and sales interviews.",
    industry: "Human Resources / Employment",
    deploymentLocations: "European Union (Germany, France, Ireland), United States (Colorado, New York City, California)",
    whoUsesIt: "Corporate hiring managers, HR business partners, and talent acquisition recruiters.",
    whoIsAffected: "Job applicants, promotion candidates, and corporate employees.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["employment"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "Fine-tuned Transformer on historical enterprise hiring records",
    decisionsAutomated: true,
    unstructuredNotes: "Deployed as an integrated applicant ranking engine in Workday. Calculates 0-100 candidate viability index scores.",
    regulatoryFocus: "EU AI Act Annex III (Employment) + NYC Local Law 144 (AEDT) + Colorado SB 24-205",
    expectedTier: "High Risk (Annex III Point 4)",
  },
  {
    systemName: "CrediPulse Underwriting & Loan Decision Engine",
    whatItDoes: "Analyzes banking transactions, credit bureau histories, and debt-to-income ratios to predict default probability.",
    intendedPurpose: "Automate consumer credit card approvals, personal loan limits, and mortgage interest rate pricing.",
    industry: "Financial Services & Consumer Lending",
    deploymentLocations: "European Union, United States (Colorado, California, New York, Texas)",
    whoUsesIt: "Retail loan officers, underwriting risk teams, and automated credit servers.",
    whoIsAffected: "Consumer credit applicants and mortgage borrowers.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["finance"],
    humanOversightDegree: "in-the-loop",
    modelProvider: "LightGBM + Deep Learning ensemble trained on credit bureau datasets",
    decisionsAutomated: true,
    unstructuredNotes: "Generates automated denial letters and adverse action risk disclosures. Direct consequential lending determinations.",
    regulatoryFocus: "EU AI Act Annex III (Credit Scoring) + Colorado SB 24-205 (Financial Services)",
    expectedTier: "High Risk (Annex III Point 5b)",
  },
  {
    systemName: "TriagePulse Emergency Deterioration Classifier",
    whatItDoes: "Predicts acute patient deterioration, septic shock probability, and ICU admission urgency from telemetry feeds.",
    intendedPurpose: "Prioritize emergency department intake queues and alert rapid response teams to decompensating patients.",
    industry: "Healthcare & Critical Medicine",
    deploymentLocations: "European Union (Germany, Netherlands), United States (Colorado, Nationwide)",
    whoUsesIt: "Emergency room triage nurses, ICU intensivists, and attending physicians.",
    whoIsAffected: "Hospital emergency department patients.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: true,
    affectedRegulatedAreas: ["healthcare"],
    humanOversightDegree: "in-the-loop",
    modelProvider: "Biomedical Transformer + Recurrent Neural Network trained on EHR records",
    decisionsAutomated: false,
    unstructuredNotes: "Advisory acuity score presented on nurse dashboard with mandatory clinician sign-off before queue reprioritization.",
    regulatoryFocus: "EU AI Act Annex III (Medical/Emergency Triage) + HIPAA + GDPR Health Data Protections",
    expectedTier: "High Risk (Annex III Point 5a)",
  },
  {
    systemName: "TenantShield Resident Screening & Eviction Scorer",
    whatItDoes: "Evaluates prospective tenant rental history, court civil records, eviction registries, and rent-to-income ratios.",
    intendedPurpose: "Generate tenant reliability risk scores and recommend approval, deposit surcharges, or lease rejections.",
    industry: "Real Estate & Property Management",
    deploymentLocations: "United States (Colorado, California, Washington, New York)",
    whoUsesIt: "Property managers, residential leasing agents, and landlord associations.",
    whoIsAffected: "Apartment applicants and residential tenants.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["housing"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "Supervised Gradient Boosted Decision Trees trained on leasing outcomes",
    decisionsAutomated: true,
    unstructuredNotes: "Substantial factor in rental housing availability. Directly triggers Colorado SB 205 housing protections.",
    regulatoryFocus: "Colorado SB 24-205 (Consequential Housing Decision) + Fair Housing Act (FHA)",
    expectedTier: "High-Risk AI System (US Colorado)",
  },
  {
    systemName: "BiometricGate Airport Border Access Sentinel",
    whatItDoes: "Performs 1-to-N automated facial biometric verification and emotional agitation detection for passport checkpoints.",
    intendedPurpose: "Automate international border e-gate entry validation and alert security personnel to anomalies.",
    industry: "Government Border Security & Transportation",
    deploymentLocations: "European Union (Schengen Area Borders), United Kingdom",
    whoUsesIt: "Border control officers and airport security authorities.",
    whoIsAffected: "International airline travelers and transit passengers.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: true,
    affectedRegulatedAreas: ["public_services"],
    humanOversightDegree: "in-the-loop",
    modelProvider: "Deep ResNet-101 Facial Embeddings + Multi-task Biometric Classifier",
    decisionsAutomated: false,
    unstructuredNotes: "Real-time biometric categorization and remote identification in publicly accessible spaces.",
    regulatoryFocus: "EU AI Act Article 5 / Annex III Point 1 (Remote Biometric Identification)",
    expectedTier: "High Risk (Annex III Point 1) / Article 5 Review",
  },
  {
    systemName: "EduProctor Exam Integrity & Proctoring Monitor",
    whatItDoes: "Analyzes student webcams, gaze tracking, audio room acoustics, and browser tabs during remote university exams.",
    intendedPurpose: "Detect unauthorized collaboration, academic dishonesty, and issue integrity flags to course professors.",
    industry: "Higher Education & Remote Testing",
    deploymentLocations: "European Union (Spain, Italy), United States (California, Colorado, Massachusetts)",
    whoUsesIt: "University exam proctors and academic integrity review boards.",
    whoIsAffected: "Undergraduate and graduate university students.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: true,
    affectedRegulatedAreas: ["education"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "Computer Vision Gaze Estimator + Acoustic Event Detection CNN",
    decisionsAutomated: false,
    unstructuredNotes: "Determines student test validity and flags instances for academic suspension or disciplinary hearings.",
    regulatoryFocus: "EU AI Act Annex III Point 3 (Education & Vocational Training)",
    expectedTier: "High Risk (Annex III Point 3)",
  },
  {
    systemName: "GridGuardian Smart Electric Distribution Balancer",
    whatItDoes: "Controls electrical transformer load dispatch, automated substation switching, and fault isolation in power grids.",
    intendedPurpose: "Prevent municipal blackout cascades and dynamically balance intermittent renewable solar and wind inputs.",
    industry: "Energy Utilities & Critical Infrastructure",
    deploymentLocations: "European Union (Germany, Austria, Poland), United States (Western Interconnection)",
    whoUsesIt: "Power grid control room dispatchers and electrical utility operators.",
    whoIsAffected: "Municipal residents and industrial power consumers.",
    makesDecisionsAboutPeople: false,
    processesPersonalData: false,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["critical_infrastructure"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "Deep Reinforcement Learning + Real-time Power Flow Simulator",
    decisionsAutomated: true,
    unstructuredNotes: "Safety component in management and operation of critical electricity infrastructure.",
    regulatoryFocus: "EU AI Act Annex III Point 2 (Critical Infrastructure)",
    expectedTier: "High Risk (Annex III Point 2)",
  },
  {
    systemName: "OmniChat Public E-Commerce Assistant",
    whatItDoes: "Conversational generative AI agent answering customer inquiries regarding order status, product sizing, and returns.",
    intendedPurpose: "Provide instant 24/7 web chat support and assist customers with product recommendations.",
    industry: "Retail & E-Commerce",
    deploymentLocations: "European Union, United States (California, New York, Texas), Global",
    whoUsesIt: "Public website visitors and online shopping consumers.",
    whoIsAffected: "Online retail shoppers.",
    makesDecisionsAboutPeople: false,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: [],
    humanOversightDegree: "in-the-loop",
    modelProvider: "Google Gemini 2.5 Flash / OpenAI GPT-4o API",
    decisionsAutomated: false,
    unstructuredNotes: "Generates synthetic conversational text. Does not make legal or consequential determinations about people.",
    regulatoryFocus: "EU AI Act Article 50 (Transparency & Chatbot Disclosure Obligations)",
    expectedTier: "Limited Risk (Transparency Required)",
  },
  {
    systemName: "AgriDrone Autonomous Crop & Soil Nitrogen Analyzer",
    whatItDoes: "Processes multispectral drone aerial imagery to compute NDVI vegetation health indices and fertilizer needs.",
    intendedPurpose: "Optimize precision tractor spraying routes and reduce environmental pesticide runoff.",
    industry: "Agriculture & Farming",
    deploymentLocations: "European Union (France, Spain), United States (Iowa, Nebraska, California)",
    whoUsesIt: "Agricultural agronomists and commercial farm managers.",
    whoIsAffected: "Farm operations (no individual people affected).",
    makesDecisionsAboutPeople: false,
    processesPersonalData: false,
    processesSensitiveData: false,
    affectedRegulatedAreas: [],
    humanOversightDegree: "over-the-loop",
    modelProvider: "YOLOv9 Multispectral Computer Vision Object Detector",
    decisionsAutomated: false,
    unstructuredNotes: "Analyzes non-personal satellite and aerial farm imagery. Purely industrial agricultural utility.",
    regulatoryFocus: "EU AI Act Non-High Risk / Minimal Risk Baseline",
    expectedTier: "Minimal Risk",
  },
  {
    systemName: "ClaimAdjust Auto Accident Estimator & Damage Scorer",
    whatItDoes: "Analyzes vehicle crash photographs to predict vehicle repair costs, structural total-loss status, and policy payout sums.",
    intendedPurpose: "Expedite motor vehicle property insurance claim adjudication and detect fraudulent staging.",
    industry: "Property & Casualty Insurance",
    deploymentLocations: "United States (Colorado, California, Florida, Illinois), European Union",
    whoUsesIt: "Insurance claims adjusters and fraud investigation units.",
    whoIsAffected: "Motor vehicle insurance policyholders and accident victims.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["insurance", "finance"],
    humanOversightDegree: "in-the-loop",
    modelProvider: "Multi-view Convolutional Vision Model + Tabular Gradient Boosted Claim Regressor",
    decisionsAutomated: false,
    unstructuredNotes: "Recommends insurance coverage payouts and settlement offers. Direct substantial factor under Colorado SB 205.",
    regulatoryFocus: "Colorado SB 24-205 (Insurance Services) + EU AI Act Annex III",
    expectedTier: "High-Risk AI System (US Colorado)",
  },
  {
    systemName: "StoreVision Shelf Stock & Inventory Scanner",
    whatItDoes: "Fixed overhead ceiling cameras detect out-of-stock items, misplaced retail boxes, and shelf replenishment needs.",
    intendedPurpose: "Alert store stock clerks to empty grocery shelves in real time.",
    industry: "Retail Operations & Logistics",
    deploymentLocations: "European Union (Germany, France), United States (Nationwide)",
    whoUsesIt: "Store inventory clerks and shift managers.",
    whoIsAffected: "Store logistics employees (no personal customer tracking).",
    makesDecisionsAboutPeople: false,
    processesPersonalData: false,
    processesSensitiveData: false,
    affectedRegulatedAreas: [],
    humanOversightDegree: "over-the-loop",
    modelProvider: "Edge TPU MobileNet Computer Vision Model",
    decisionsAutomated: false,
    unstructuredNotes: "Cameras point strictly at store merchandise shelves. Facial recognition and customer tracking are disabled.",
    regulatoryFocus: "EU AI Act Minimal Risk (Non-personal operational AI)",
    expectedTier: "Minimal Risk",
  },
  {
    systemName: "WorkplacePulse Remote Worker Keystroke & Productivity Scorer",
    whatItDoes: "Monitors remote employee mouse movements, active application dwell times, and web browsing to compute worker engagement.",
    intendedPurpose: "Provide employee productivity scores used during quarterly performance reviews and compensation decisions.",
    industry: "Corporate Workforce Analytics",
    deploymentLocations: "European Union (Ireland), United States (Colorado, New York, Texas)",
    whoUsesIt: "Corporate managers, HR personnel, and operations directors.",
    whoIsAffected: "Full-time remote enterprise employees and contractors.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["employment"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "Time-series anomaly detector + Behavioral telemetry regressor",
    decisionsAutomated: true,
    unstructuredNotes: "Directly impacts employee performance ratings, bonus allocations, and termination decisions.",
    regulatoryFocus: "EU AI Act Annex III Point 4 (Employment & Worker Management) + GDPR Article 22",
    expectedTier: "High Risk (Annex III Point 4)",
  },
  {
    systemName: "FleetPilot Autonomous Forklift Navigation & Obstacle Avoidance",
    whatItDoes: "Guides unmanned autonomous industrial forklifts through logistics distribution centers with LiDAR and stereo vision.",
    intendedPurpose: "Safely navigate pallet transport through shared aisles with human warehouse workers.",
    industry: "Industrial Machinery & Supply Chain",
    deploymentLocations: "European Union (Germany, Belgium), United States (Ohio, Pennsylvania)",
    whoUsesIt: "Warehouse logistics supervisors and automated fleet dispatchers.",
    whoIsAffected: "Warehouse floor workers and machinery operators.",
    makesDecisionsAboutPeople: false,
    processesPersonalData: false,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["critical_infrastructure"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "3D LiDAR PointNet + Real-time ROS 2 Path Planning Controller",
    decisionsAutomated: true,
    unstructuredNotes: "Safety component for heavy machinery falling under EU Machinery Regulation 2023/1230 & EU AI Act Annex I.",
    regulatoryFocus: "EU AI Act Annex I (Machinery Safety Legislation) + OSHA",
    expectedTier: "High Risk (Annex I Safety Component)",
  },
  {
    systemName: "PatrolRoute Predictive Police Resource Allocator",
    whatItDoes: "Analyzes historic crime dispatch logs, weather patterns, and geographic census data to forecast property theft hot spots.",
    intendedPurpose: "Recommend municipal police cruiser patrol beats and surveillance car distribution.",
    industry: "Public Safety & Municipal Law Enforcement",
    deploymentLocations: "United States (California, Texas), European Union (Trial deployment)",
    whoUsesIt: "Municipal police department dispatch commanders.",
    whoIsAffected: "Neighborhood residents and local community members.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: ["public_services"],
    humanOversightDegree: "on-the-loop",
    modelProvider: "Spatial-Temporal Poisson Point Process Regressor",
    decisionsAutomated: false,
    unstructuredNotes: "Predicts geographic criminal likelihood. Triggers stringent review under EU Article 5 and Annex III Point 6.",
    regulatoryFocus: "EU AI Act Annex III Point 6 (Law Enforcement) / Article 5 Predictive Profiling",
    expectedTier: "High Risk (Annex III Point 6) / Restricted",
  },
  {
    systemName: "ClinicalTrial MatchIQ Patient Eligibility Screener",
    whatItDoes: "Scans electronic health records, genomic biomarkers, and oncological pathology reports to identify clinical trial candidates.",
    intendedPurpose: "Match refractory cancer patients with experimental oncology immunotherapy trials.",
    industry: "Pharmaceuticals & Clinical Research",
    deploymentLocations: "European Union (France, Germany, Sweden), United States (Nationwide)",
    whoUsesIt: "Principal clinical investigators and hospital oncology research nurses.",
    whoIsAffected: "Cancer patients seeking experimental therapies.",
    makesDecisionsAboutPeople: true,
    processesPersonalData: true,
    processesSensitiveData: true,
    affectedRegulatedAreas: ["healthcare"],
    humanOversightDegree: "in-the-loop",
    modelProvider: "Clinical BioBERT NLP Model + Genomic Variant Classifier",
    decisionsAutomated: false,
    unstructuredNotes: "Processes highly sensitive genetic and health diagnostic data. Clinical oncologist retains final veto.",
    regulatoryFocus: "EU AI Act Annex III (Healthcare) + EU Clinical Trials Regulation 536/2014 + GDPR Art 9",
    expectedTier: "High Risk (Annex III Point 5a)",
  },
  {
    systemName: "StreamGuard Live Media Hate Speech & Harassment Filter",
    whatItDoes: "Performs real-time NLP text classification on live stream chat comments to flag and suppress hate speech.",
    intendedPurpose: "Protect online broadcast audiences from coordinated toxic harassment campaigns and hate speech.",
    industry: "Digital Media & Online Social Platforms",
    deploymentLocations: "European Union, United States, Global",
    whoUsesIt: "Live streaming platform moderators and automated content safety bots.",
    whoIsAffected: "Online broadcast viewers and chat participants.",
    makesDecisionsAboutPeople: false,
    processesPersonalData: true,
    processesSensitiveData: false,
    affectedRegulatedAreas: [],
    humanOversightDegree: "in-the-loop",
    modelProvider: "RoBERTa Multi-lingual Hate Speech Classifier",
    decisionsAutomated: true,
    unstructuredNotes: "Operates as a digital services moderation classifier under EU Digital Services Act (DSA).",
    regulatoryFocus: "EU Digital Services Act (DSA) + EU AI Act Transparency",
    expectedTier: "Limited Risk (DSA Regulated)",
  },
];

let lastGeneratedIndex = -1;

export function generateRandomAISystemDemo(): DemoSystemTemplate & { demoSeedId: string } {
  // Pick an index different from the last one to ensure continuous randomization on every click
  let nextIndex: number;
  if (DEMO_ARCHETYPES.length <= 1) {
    nextIndex = 0;
  } else {
    do {
      nextIndex = Math.floor(Math.random() * DEMO_ARCHETYPES.length);
    } while (nextIndex === lastGeneratedIndex);
  }
  lastGeneratedIndex = nextIndex;

  const base = DEMO_ARCHETYPES[nextIndex];

  // Dynamic random variations (versions, enterprise releases, internal codenames, locations)
  const versions = ["v2.4", "v3.1-Enterprise", "2026.Q2", "v4.0-Pro", "v1.9-LTS", "2026.R3"];
  const randomVersion = versions[Math.floor(Math.random() * versions.length)];
  const randomId = Math.random().toString(36).substring(2, 7).toUpperCase();

  // Dynamic slight variations in model provider to keep every single click feeling alive
  const modelProviders = [
    `${base.modelProvider} (Release ${randomVersion})`,
    `${base.modelProvider} (Fine-tuned on Enterprise Dataset)`,
    `${base.modelProvider} [Engine ID: ENG-${randomId}]`,
  ];
  const selectedModelProvider = modelProviders[Math.floor(Math.random() * modelProviders.length)];

  return {
    ...base,
    systemName: `${base.systemName} ${randomVersion}`,
    modelProvider: selectedModelProvider,
    demoSeedId: `DEMO-${randomId}`,
  };
}
